"""empty message

Revision ID: 306786df0c0c
Revises: b7299b41488e
Create Date: 2022-09-16 19:21:56.527343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306786df0c0c'
down_revision = 'b7299b41488e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daysavailable', sa.String(), nullable=True))
    op.add_column('user', sa.Column('timesavailable', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'timesavailable')
    op.drop_column('user', 'daysavailable')
    # ### end Alembic commands ###
