"""empty message

Revision ID: 33f061b44742
Revises: a91f8240b586
Create Date: 2022-09-07 23:58:17.525986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f061b44742'
down_revision = 'a91f8240b586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', sa.String(length=150), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###
