"""empty message

Revision ID: 3d835ef0fe76
Revises: 33f061b44742
Create Date: 2022-09-07 23:58:50.818940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d835ef0fe76'
down_revision = '33f061b44742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=150), nullable=False))
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
