"""empty message

Revision ID: 57a1f12e591d
Revises: 7b341695f43f
Create Date: 2022-09-03 15:19:34.397166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a1f12e591d'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('trainertype', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('zipcode', sa.String(length=40), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['firstname'])
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['zipcode'])
    op.create_unique_constraint(None, 'user', ['trainertype'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'trainertype')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
