"""empty message

Revision ID: 916907916af4
Revises: e33612eb00e7
Create Date: 2022-09-06 22:53:01.063530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916907916af4'
down_revision = 'e33612eb00e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
