"""empty message

Revision ID: dd4d25bea81c
Revises: ab22e1886bb7
Create Date: 2022-09-08 22:38:24.821058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4d25bea81c'
down_revision = 'ab22e1886bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aboutme', sa.String(), nullable=True))
    op.add_column('user', sa.Column('age', sa.String(), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(), nullable=True))
    op.add_column('user', sa.Column('experience', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience')
    op.drop_column('user', 'education')
    op.drop_column('user', 'age')
    op.drop_column('user', 'aboutme')
    # ### end Alembic commands ###
