"""empty message

Revision ID: e33612eb00e7
Revises: 57a1f12e591d
Create Date: 2022-09-03 19:49:39.445060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33612eb00e7'
down_revision = '57a1f12e591d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_firstname_key', 'user', type_='unique')
    op.drop_constraint('user_lastname_key', 'user', type_='unique')
    op.drop_constraint('user_trainertype_key', 'user', type_='unique')
    op.drop_constraint('user_zipcode_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_zipcode_key', 'user', ['zipcode'])
    op.create_unique_constraint('user_trainertype_key', 'user', ['trainertype'])
    op.create_unique_constraint('user_lastname_key', 'user', ['lastname'])
    op.create_unique_constraint('user_firstname_key', 'user', ['firstname'])
    # ### end Alembic commands ###
